const GAME_DATA = {
  firstNames: [
    "Thunder", "Storm", "Shadow", "Golden", "Silver", "Dark", "Bright", "Wild",
    "Royal", "Noble", "Swift", "Midnight", "Dawn", "Crimson", "Iron", "Diamond",
    "Emerald", "Sapphire", "Ruby", "Crystal", "Phantom", "Dragon", "Phoenix",
    "Eagle", "Falcon", "Raven", "Arctic", "Desert", "Ocean", "Mountain",
    "Velvet", "Silk", "Steel", "Copper", "Bronze", "Amber", "Ivory", "Ebony",
    "Scarlet", "Azure", "Lucky", "Brave", "Fierce", "Gentle", "Proud", "Bold",
    "Mystic", "Magic", "Secret", "Silent", "Flying", "Dancing", "Blazing", "Roaring",
    "Whispering", "Galloping", "Soaring", "Shining", "Glowing", "Dazzling"
  ],
  lastNames: [
    "Star", "Light", "Fire", "Wind", "Rain", "Cloud", "Moon", "Sun",
    "Spirit", "Heart", "Dream", "Song", "Dance", "Storm", "Blaze", "Flash",
    "Arrow", "Bolt", "Strike", "Quest", "Glory", "Pride", "Honor", "Grace",
    "Charm", "Wonder", "Marvel", "Legend", "Fury", "Force", "Power", "Reign",
    "Knight", "Prince", "King", "Queen", "Dancer", "Runner", "Chaser", "Flyer",
    "Whisper", "Echo", "Shadow", "Flame", "Frost", "Breeze", "Gale", "Tempest",
    "Majesty", "Victory", "Triumph", "Fortune", "Destiny", "Phantom", "Express",
    "Missile", "Rocket", "Comet", "Meteor", "Galaxy"
  ],
  coatColors: [
    { name: "Bay", color: "#8B4513", mane: "#1a1a1a", frequency: 0.3 },
    { name: "Chestnut", color: "#CD853F", mane: "#8B4513", frequency: 0.2 },
    { name: "Dark Bay", color: "#5C3317", mane: "#1a1a1a", frequency: 0.15 },
    { name: "Grey", color: "#A0A0A0", mane: "#808080", frequency: 0.1 },
    { name: "Black", color: "#2a2a2a", mane: "#1a1a1a", frequency: 0.08 },
    { name: "Palomino", color: "#DAA520", mane: "#F5DEB3", frequency: 0.05 },
    { name: "Roan", color: "#BC8F8F", mane: "#6B3A3A", frequency: 0.05 },
    { name: "Dun", color: "#C4A265", mane: "#5C4033", frequency: 0.04 },
    { name: "Pinto", color: "#D2B48C", mane: "#1a1a1a", frequency: 0.02 },
    { name: "White", color: "#F0EAD6", mane: "#E0D8C0", frequency: 0.01 }
  ],
  jockeyFirstNames: [
    "James", "William", "Ryan", "Frankie", "Lester", "Pat", "Christophe",
    "Oisin", "Colin", "Tom", "Harry", "Jack", "Daniel", "Sean", "Michael",
    "Andrea", "Hollie", "Hayley", "Josephine", "Rachel", "Emma", "Sophie",
    "Luis", "Carlos", "Pierre", "Yutaka", "Joao", "Roberto", "Silvestre",
    "Jamie", "Kevin", "Brian", "Mark", "David", "Paul", "Ben", "Sam",
    "Luke", "Adam", "Chris", "Rob", "Neil", "Craig", "Gary", "Alan"
  ],
  jockeySurnames: [
    "Murphy", "Moore", "Dettori", "Piggott", "Eddery", "Fallon", "Soumillon",
    "Buick", "Doyle", "Marquand", "O'Brien", "Spencer", "Crowley", "de Sousa",
    "Kirby", "Curtis", "Tudhope", "Havlin", "Kingscote", "Probert",
    "McDonald", "Lane", "McEvoy", "Bowman", "Payne", "Kah", "Purton",
    "Moreira", "Lemaire", "Barzalona", "Peslier", "Guyon", "Benoist",
    "Heffernan", "Keane", "Hussey", "Manning", "Foley", "Whelan", "Hayes"
  ],
  tracks: [
    { name: "Royal Ascot", country: "GB", surface: "Turf", prestige: 5, distances: [1000, 1200, 1400, 1600, 2000, 2400, 4000] },
    { name: "Epsom Downs", country: "GB", surface: "Turf", prestige: 5, distances: [1200, 1400, 1600, 2400] },
    { name: "Newmarket", country: "GB", surface: "Turf", prestige: 5, distances: [1000, 1200, 1400, 1600, 2000, 2400] },
    { name: "York", country: "GB", surface: "Turf", prestige: 4, distances: [1000, 1200, 1400, 1600, 2000, 2400] },
    { name: "Cheltenham", country: "GB", surface: "Turf", prestige: 5, distances: [3200, 4000, 4800, 5200] },
    { name: "Aintree", country: "GB", surface: "Turf", prestige: 5, distances: [3200, 4000, 5200, 7200] },
    { name: "Goodwood", country: "GB", surface: "Turf", prestige: 4, distances: [1000, 1200, 1600, 2000, 2400] },
    { name: "Sandown", country: "GB", surface: "Turf", prestige: 3, distances: [1000, 1200, 1400, 1600, 2000, 3200] },
    { name: "Kempton", country: "GB", surface: "AW", prestige: 3, distances: [1000, 1200, 1400, 1600, 2000] },
    { name: "Longchamp", country: "FR", surface: "Turf", prestige: 5, distances: [1200, 1400, 1600, 2000, 2400, 4000] },
    { name: "Chantilly", country: "FR", surface: "Turf", prestige: 4, distances: [1200, 1600, 2000, 2400] },
    { name: "Meydan", country: "UAE", surface: "Dirt", prestige: 5, distances: [1200, 1600, 1800, 2000, 2400, 3200] },
    { name: "Churchill Downs", country: "US", surface: "Dirt", prestige: 5, distances: [1200, 1400, 1600, 2000] },
    { name: "Saratoga", country: "US", surface: "Dirt", prestige: 4, distances: [1200, 1400, 1600, 1800, 2000] },
    { name: "Leopardstown", country: "IE", surface: "Turf", prestige: 4, distances: [1200, 1400, 1600, 2000, 2400, 3200] },
    { name: "The Curragh", country: "IE", surface: "Turf", prestige: 5, distances: [1000, 1200, 1400, 1600, 2000, 2400] },
    { name: "Flemington", country: "AU", surface: "Turf", prestige: 5, distances: [1200, 1400, 1600, 2000, 2400, 3200] },
    { name: "Sha Tin", country: "HK", surface: "Turf", prestige: 5, distances: [1200, 1400, 1600, 2000, 2400] },
    { name: "Tokyo", country: "JP", surface: "Turf", prestige: 5, distances: [1400, 1600, 1800, 2000, 2400, 3200] },
    { name: "Wolverhampton", country: "GB", surface: "AW", prestige: 1, distances: [1200, 1400, 1600, 2000] },
    { name: "Lingfield", country: "GB", surface: "AW", prestige: 2, distances: [1000, 1200, 1400, 1600, 2000] },
    { name: "Catterick", country: "GB", surface: "Turf", prestige: 1, distances: [1000, 1200, 1400, 1600] },
    { name: "Plumpton", country: "GB", surface: "Turf", prestige: 1, distances: [3200, 4000] },
    { name: "Fontwell", country: "GB", surface: "Turf", prestige: 1, distances: [3200, 4000, 4800] },
  ],
  raceClasses: [
    { class: 7, name: "Class 7", minRating: 0, maxRating: 45, prizeMoney: 3000 },
    { class: 6, name: "Class 6", minRating: 0, maxRating: 55, prizeMoney: 5000 },
    { class: 5, name: "Class 5", minRating: 46, maxRating: 65, prizeMoney: 8000 },
    { class: 4, name: "Class 4", minRating: 56, maxRating: 75, prizeMoney: 12000 },
    { class: 3, name: "Class 3", minRating: 66, maxRating: 85, prizeMoney: 20000 },
    { class: 2, name: "Class 2", minRating: 76, maxRating: 100, prizeMoney: 40000 },
    { class: 1, name: "Class 1", minRating: 86, maxRating: 115, prizeMoney: 75000 },
    { class: 0, name: "Group 3", minRating: 100, maxRating: 125, prizeMoney: 120000 },
    { class: -1, name: "Group 2", minRating: 110, maxRating: 135, prizeMoney: 200000 },
    { class: -2, name: "Group 1", minRating: 120, maxRating: 150, prizeMoney: 500000 },
  ],
  groundTypes: ["Hard", "Firm", "Good to Firm", "Good", "Good to Soft", "Soft", "Heavy"],
  trainingRegimes: [
    { id: "rest", name: "Rest", icon: "🛏️", fitnessChange: -5, staminaChange: 0, speedChange: -1, healthRisk: 0, moraleChange: 3, description: "Complete rest. Recovers morale and reduces fitness." },
    { id: "light", name: "Light Work", icon: "🚶", fitnessChange: 2, staminaChange: 1, speedChange: 0, healthRisk: 0.01, moraleChange: 1, description: "Easy canters and walking. Gentle fitness building." },
    { id: "moderate", name: "Moderate", icon: "🏃", fitnessChange: 5, staminaChange: 2, speedChange: 1, healthRisk: 0.03, moraleChange: 0, description: "Regular gallops. Balanced training approach." },
    { id: "intense", name: "Intense", icon: "💪", fitnessChange: 8, staminaChange: 3, speedChange: 2, healthRisk: 0.08, moraleChange: -2, description: "Hard training. Fast improvement but injury risk." },
    { id: "speed", name: "Speed Work", icon: "⚡", fitnessChange: 3, staminaChange: -1, speedChange: 4, healthRisk: 0.06, moraleChange: -1, description: "Sprint drills. Boosts speed at cost of stamina." },
    { id: "stamina", name: "Endurance", icon: "🏔️", fitnessChange: 4, staminaChange: 4, speedChange: -1, healthRisk: 0.04, moraleChange: -1, description: "Long distance work. Builds staying power." },
    { id: "swim", name: "Swimming", icon: "🏊", fitnessChange: 3, staminaChange: 2, speedChange: 0, healthRisk: 0.005, moraleChange: 2, description: "Pool sessions. Low impact, good recovery." },
    { id: "hills", name: "Hill Work", icon: "⛰️", fitnessChange: 6, staminaChange: 3, speedChange: 2, healthRisk: 0.05, moraleChange: -1, description: "Uphill gallops. Builds power and stamina." },
  ],
  months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],

  championRaces: [
    { name: "The Derby", track: "Epsom Downs", distance: 2400, month: 5, class: -2, surface: "Turf", ageRestriction: 3, prize: 1500000 },
    { name: "2000 Guineas", track: "Newmarket", distance: 1600, month: 4, class: -2, surface: "Turf", ageRestriction: 3, prize: 1000000 },
    { name: "1000 Guineas", track: "Newmarket", distance: 1600, month: 4, class: -2, surface: "Turf", ageRestriction: 3, prize: 800000 },
    { name: "St Leger", track: "York", distance: 2400, month: 8, class: -2, surface: "Turf", ageRestriction: 3, prize: 700000 },
    { name: "Gold Cup", track: "Royal Ascot", distance: 4000, month: 5, class: -2, surface: "Turf", ageRestriction: null, prize: 1000000 },
    { name: "Champion Stakes", track: "Royal Ascot", distance: 2000, month: 9, class: -2, surface: "Turf", ageRestriction: null, prize: 1200000 },
    { name: "Prix de l'Arc de Triomphe", track: "Longchamp", distance: 2400, month: 9, class: -2, surface: "Turf", ageRestriction: null, prize: 2500000 },
    { name: "Dubai World Cup", track: "Meydan", distance: 2000, month: 2, class: -2, surface: "Dirt", ageRestriction: null, prize: 5000000 },
    { name: "Kentucky Derby", track: "Churchill Downs", distance: 2000, month: 4, class: -2, surface: "Dirt", ageRestriction: 3, prize: 3000000 },
    { name: "Melbourne Cup", track: "Flemington", distance: 3200, month: 10, class: -2, surface: "Turf", ageRestriction: null, prize: 4000000 },
    { name: "Hong Kong Cup", track: "Sha Tin", distance: 2000, month: 11, class: -2, surface: "Turf", ageRestriction: null, prize: 2000000 },
    { name: "Japan Cup", track: "Tokyo", distance: 2400, month: 10, class: -2, surface: "Turf", ageRestriction: null, prize: 3000000 },
    { name: "Gold Cup (Cheltenham)", track: "Cheltenham", distance: 5200, month: 2, class: -2, surface: "Turf", ageRestriction: null, prize: 600000 },
    { name: "Grand National", track: "Aintree", distance: 7200, month: 3, class: -2, surface: "Turf", ageRestriction: null, prize: 1000000 },
    { name: "King George VI Chase", track: "Kempton", distance: 4800, month: 11, class: -2, surface: "Turf", ageRestriction: null, prize: 500000 },
  ],

  distanceCategories: [
    { name: "Sprint", min: 1000, max: 1200 },
    { name: "Miler", min: 1400, max: 1600 },
    { name: "Middle Distance", min: 1800, max: 2400 },
    { name: "Stayer", min: 2800, max: 4000 },
    { name: "Extreme", min: 4000, max: 8000 },
  ],

  weeklyExpenses: {
    perHorse: 350,
    stableUpkeep: 500,
    jockeyRetainer: 200,
  },
};
